# Generated by Django 4.2.16 on 2024-11-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_dislikes_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('MOVIE', '영화'), ('TICKET', '티켓 거래'), ('CHAT', '잡담')], default='CHAT', max_length=10),
        ),
    ]
