# Generated by Django 4.2.16 on 2024-11-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_director_genre_prize_preference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prize',
            new_name='Award',
        ),
    ]
