# Generated by Django 4.2.16 on 2024-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_prize_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_awards',
            field=models.ManyToManyField(blank=True, to='accounts.award'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_directors',
            field=models.ManyToManyField(blank=True, to='accounts.director'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='accounts.genre'),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
