# Generated by Django 4.2.16 on 2024-11-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_award_year_user_favorite_awards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='year',
        ),
    ]
