# Generated by Django 4.2.16 on 2024-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_weather'),
        ('accounts', '0007_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
    ]
