# Generated by Django 4.2.16 on 2024-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_recommended_temperature'),
        ('accounts', '0008_alter_user_favorite_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='movies.genre'),
        ),
    ]
