# Generated by Django 4.2.16 on 2024-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
