# Generated by Django 4.2.16 on 2024-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_genre_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
