# Generated by Django 4.2.16 on 2024-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='weather',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
