# Generated by Django 4.2.16 on 2024-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommended_temperature',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
